# Generated by Django 4.2.10 on 2024-03-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electricity_bill", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="due_date",
            field=models.DateField(default=None),
        ),
    ]
